import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {initialState,recruit,release,openPack,PACKS,autoFill,REQUIREMENTS,restore} from './economy.js';
const data=JSON.parse(readFileSync(new URL('../public/data/catalog.json',import.meta.url)));const players=data.players;
test('catalog is complete by identity, starter pool is 20% and capped at 80',()=>{assert.equal(new Set(players.map(p=>p.id)).size,players.length);const active=players.filter(p=>p.eligible),starter=players.filter(p=>p.starter);assert.equal(new Set(active.map(p=>p.team)).size,32);assert.equal(starter.length,Math.round(active.length*.2));assert(starter.every(p=>p.eligible&&p.overall<=80));assert(players.every(p=>Number.isFinite(p.cost)&&p.cost>0));});
test('starter funds cover every required position',()=>{const s=autoFill(initialState(),players);for(const [pos,min] of Object.entries(REQUIREMENTS))assert(s.roster.filter(r=>players.find(p=>p.id===r.id).position===pos).length>=min);assert(s.credits>=0);});
test('buy and release preserve funds and reject duplicates, locked and unaffordable players',()=>{const s=initialState(),p=players.find(p=>p.starter);const bought=recruit(s,p);assert.equal(release(bought,p.id).credits,s.credits);assert.throws(()=>recruit(bought,p));assert.throws(()=>recruit({...s,credits:0},p));assert.throws(()=>recruit(s,players.find(p=>p.eligible&&!p.starter)));});
test('packs charge once, contain eligible unique unlocks and do not grant roster members',()=>{for(const pack of PACKS){const s=initialState();const result=openPack(s,pack,players,()=>.5);assert.equal(result.state.tokens,s.tokens-pack.cost);assert.equal(result.state.roster.length,0);assert.equal(new Set(result.cards.map(p=>p.id)).size,pack.count);assert(result.cards.every(p=>!p.starter&&p.overall>=pack.min&&p.overall<=pack.max));assert.throws(()=>openPack({...s,tokens:0},pack,players));assert.throws(()=>openPack(s,pack,[],()=>0));}});
test('milestones cannot be farmed by releasing and re-signing',()=>{let s=initialState();const ps=players.filter(p=>p.starter).sort((a,b)=>a.cost-b.cost).slice(0,10);for(const p of ps)s=recruit(s,p);assert.equal(s.tokens,7);s=recruit(release(s,ps[0].id),ps[0]);assert.equal(s.tokens,7);});
test('save reload restores purchases and corrupt data falls back',()=>{const s=recruit(initialState(),players.find(p=>p.starter));assert.deepEqual(restore(JSON.stringify(s),players),s);assert.deepEqual(restore('{bad',players),initialState());});

test('profile measurements preserve unavailable data and cover roster vitals',()=>{const active=players.filter(p=>p.eligible);assert(active.every(p=>p.bio.heightInches>0&&p.bio.weightLbs>0));const tested=active.filter(p=>p.combine.fortySeconds!==null);assert(tested.length>500);assert(tested.every(p=>p.combine.fortySeconds>3&&p.combine.fortySeconds<7));assert(active.some(p=>p.combine.fortySeconds===null));assert(active.every(p=>p.seasonStats['2025']&&p.seasonStats['2026']));});
test('profile formatting handles birthdays, missing values and zero denominators',async()=>{const {heightLabel,ageAt,rate}=await import('./profile.js');assert.equal(heightLabel(75),'6′ 3″');assert.equal(heightLabel(null),'Not reported');assert.equal(ageAt('2000-09-29','2026-09-28'),25);assert.equal(ageAt('2000-09-28','2026-09-28'),26);assert.equal(rate(0,5),0);assert.equal(rate(0,0),null);assert.equal(rate(null,5),null);});
