import React,{useState} from 'react';
import {heightLabel,ageAt,rate,STAT_GROUPS,DEFENSE,LABELS} from './profile';
const reported=(v,suffix='')=>v===null||v===undefined?'Not reported':`${v}${suffix}`;
function Facts({items}){return <dl className="profile-facts">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd className={value==='Not reported'?'unreported':''}>{value}</dd></div>)}</dl>}
export function PlayerProfile({player:p,season,asOf}){
 const [year,setYear]=useState(String(season));const b=p.bio||{},c=p.combine||{},stats=p.seasonStats?.[year]||{};const age=ageAt(b.birthDate,asOf);const hasStats=Object.values(stats).some(v=>v!==null&&v!==undefined);const fmt=v=>v===null||v===undefined?'—':Number.isInteger(v)?v.toLocaleString():v.toFixed(1);
 const derived=[];
 if(p.position==='QB')derived.push(['Completion rate',rate(stats.completions,stats.attempts,100),'%'],['Yards / attempt',rate(stats.passing_yards,stats.attempts),'']);
 if(['RB','WR','QB'].includes(p.position))derived.push(['Yards / carry',rate(stats.rushing_yards,stats.carries),'']);
 if(['RB','WR','TE'].includes(p.position))derived.push(['Catch rate',rate(stats.receptions,stats.targets,100),'%'],['Yards / reception',rate(stats.receiving_yards,stats.receptions),'']);
 if(p.position==='K')derived.push(['Field goal accuracy',rate(stats.fg_made,stats.fg_att,100),'%']);
 if(p.position==='P')derived.push(['Net yards / punt',rate(stats.pt_net_yards,stats.pt_att),'']);
 return <div className="expanded-profile"><section className="profile-section"><div className="profile-section-heading"><h3>Player vitals</h3><span>ROSTER DATA</span></div><Facts items={[
 ['Height',heightLabel(b.heightInches)],['Weight',reported(b.weightLbs,' lb')],['Age',reported(age,' years')],['NFL experience',b.experienceYears===0?'Rookie':reported(b.experienceYears,' years')],['College',b.college||'Not reported'],['Birth date',b.birthDate||'Not reported'],['Entered NFL',reported(b.entryYear)],['Draft pick',b.draftPick?`#${b.draftPick}${b.draftTeam?` · ${b.draftTeam}`:''}`:'Not reported'],['Position',`${p.detailPosition} · ${p.position}`],['Roster status',({ACT:'Active',INA:'Inactive',RES:'Reserve',DEV:'Practice squad'})[p.status]||p.status]
 ]}/></section>
 <section className="profile-section"><div className="profile-section-heading"><h3>Speed & athletic testing</h3><span>{c.year?`${c.year} COMBINE`:'COMBINE DATA'}</span></div><div className="speed-highlight"><div><span>40-YARD DASH</span><strong>{c.fortySeconds!=null?c.fortySeconds.toFixed(2):'—'}<small>{c.fortySeconds!=null?'SEC':'NOT REPORTED'}</small></strong></div><p>{c.fortySeconds!=null?'Recorded combine sprint time. Lower is faster.':'No recorded 40-yard dash in the linked combine data.'}</p></div><Facts items={[
 ['Bench press · 225 lb',reported(c.benchReps,' reps')],['Vertical jump',reported(c.verticalInches,' in')],['Broad jump',reported(c.broadJumpInches,' in')],['3-cone drill',reported(c.threeConeSeconds,' sec')],['20-yard shuttle',reported(c.shuttleSeconds,' sec')]
 ]}/><p className="profile-footnote">Historical pre-draft measurements, not current playing speed. Missing drills stay unreported. Combine records are matched by player ID, never guessed from names.</p></section>
 <section className="profile-section"><div className="profile-section-heading"><h3>Season performance</h3><label className="season-selector"><span className="sr-only">Stats season</span><select value={year} onChange={e=>setYear(e.target.value)}>{[season,season-1].map(y=><option key={y}>{y}</option>)}</select></label></div><p className="profile-footnote">Regular season · {stats.games==null?'Games not reported':`${stats.games} games played`} · Zero means a recorded zero; — means unavailable.</p>{hasStats?<>{(STAT_GROUPS[p.position]||DEFENSE).map(([name,keys])=><div className="stat-group" key={name}><h4>{name}</h4><dl className="stat-table">{keys.map(k=><div key={k}><dt>{LABELS[k]}</dt><dd>{fmt(stats[k])}</dd></div>)}</dl></div>)}{derived.length>0&&<div className="stat-group"><h4>Efficiency</h4><dl className="stat-table">{derived.map(([label,v,suffix])=><div key={label}><dt>{label}</dt><dd>{v==null?'—':v.toFixed(1)+suffix}</dd></div>)}</dl></div>}</>:<p className="muted">No recorded season statistics for this player in this feed.</p>}{['OL','LS'].includes(p.position)&&<p className="profile-footnote">Individual blocking grades, pressures allowed and long-snap accuracy are not supplied by these datasets.</p>}</section>
 </div>
}
