import React,{useMemo,useState} from 'react';
import {ACHIEVEMENTS,STAT_LABELS,careerStats} from './gameStats.js';
const groups={Participation:['snaps','blocks','blocksShed'],Passing:['passAttempts','completions','passingYards','passingTDs','interceptionsThrown'],Rushing:['rushAttempts','rushingYards','rushingTDs','longestRush'],Receiving:['targets','receptions','receivingYards','receivingTDs','longestReception'],Defense:['tackles','sacks','interceptions'], 'Special teams':['fieldGoalAttempts','fieldGoals','extraPointAttempts','extraPoints','punts','puntYards','returns','returnYards','returnTDs']};
const num=n=>(n||0).toLocaleString();const rate=(a,b)=>b?`${a||0}/${b} (${Math.round((a||0)/b*100)}%)`:'0/0 (—)';
export function PlayerGameStats({history,playerId}){const p=careerStats(history).players[playerId];return <section className="game-panel"><h3>Your franchise stats</h3><p className="muted">Completed games in this save · separate from NFL season data</p>{p?<dl className="stat-table">{Object.entries(p.stats).filter(([key,n])=>n||key==='games').map(([key,n])=><div key={key}><dt>{STAT_LABELS[key]||key}</dt><dd>{num(n)}</dd></div>)}</dl>:<p>No recorded appearances yet.</p>}</section>}
export function StatsHub({state}){
 const history=state.history||[],career=useMemo(()=>careerStats(history),[history]);
 const [page,setPage]=useState(state.game?.completed?'games':'career'),[gameId,setGameId]=useState(history[0]?.id||''),[side,setSide]=useState('home'),[category,setCategory]=useState('Passing'),[query,setQuery]=useState(''),[sort,setSort]=useState('passingYards'),[player,setPlayer]=useState(null);
 const game=history.find(g=>g.id===gameId),box=game?.boxScore;
 const data=page==='games'?(box?.[side]||{team:{},players:{}}):career;
 const keys=groups[category];const rows=Object.values(data.players).filter(p=>keys.some(k=>p.stats[k])&&p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(b.stats[sort]||0)-(a.stats[sort]||0)||a.name.localeCompare(b.name));
 const earned=new Set(state.achievements||[]),rewards=ACHIEVEMENTS.filter(a=>earned.has(a.id)).reduce((n,a)=>n+a.reward,0);
 function section(id){setPage(id);setPlayer(null)}
 return <div className="stats-hub"><div className="section-head"><div><span className="eyebrow">FRANCHISE RECORD BOOK</span><h2>Every game counts.</h2></div><span>{history.length} completed games</span></div><nav className="stats-tabs">{[['career','Career stats'],['games','Game history'],['achievements','Achievements']].map(([id,label])=><button key={id} className={page===id?'selected':''} onClick={()=>section(id)}>{label}</button>)}</nav>
 {page==='achievements'?<><div className="game-panel"><h3>{earned.size} / {ACHIEVEMENTS.length} achievements</h3><p>{num(rewards)} credits earned · Rewards are automatically paid once when a game finishes.</p><p className="muted">Progress uses your franchise’s completed, tracked games. Replays and discarded games do not earn progress.</p></div><div className="achievement-grid">{ACHIEVEMENTS.map(a=>{const progress=Math.max(0,career.team[a.key]||0),done=earned.has(a.id);return <article className={`achievement-card ${done?'earned':''}`} key={a.id}><span className="eyebrow">{done?'EARNED':'IN PROGRESS'} · {num(a.reward)} CR</span><h3>{a.name}</h3><p>{num(a.goal)} {STAT_LABELS[a.key]?.toLowerCase()||a.key}</p><progress value={Math.min(a.goal,progress)} max={a.goal}/><small>{num(progress)} / {num(a.goal)}{done?' · Reward paid':''}</small></article>})}</div></>:<>
 {page==='games'?<><label className="setting-label">Select a completed game<select value={gameId} onChange={e=>{setGameId(e.target.value);setPlayer(null)}}><option value="" disabled>Choose game</option>{history.map((g,i)=><option key={g.id} value={g.id}>Game {history.length-i} · {g.result} vs {g.opponent} · {g.score.home}–{g.score.away}{g.completedAt?' · '+new Date(g.completedAt).toLocaleDateString():''}</option>)}</select></label>{game?<section className="game-panel"><span className="eyebrow">FINAL · {game.result==='W'?'WIN':game.result==='L'?'LOSS':'TIE'}</span><h2>{game.name||'Your franchise'} {game.score.home} — {game.score.away} {game.opponent}</h2>{game.achievementCredits>0&&<div className="stats-reward" role="status">+{num(game.achievementCredits)} credits earned{(game.achievements||[]).map(id=><span key={id}>{ACHIEVEMENTS.find(a=>a.id===id)?.name}</span>)}</div>}{!box?<p className="muted">This game predates stat tracking. Its score is preserved; player stats are unavailable.</p>:<>{box.partial&&<p className="notice">Tracking began during this game. This box score includes only the recorded plays.</p>}<div className="stats-scroll"><table className="box-table"><thead><tr><th>Team stats</th><th>{game.name||'Your franchise'}</th><th>{game.opponent}</th></tr></thead><tbody>{['passingYards','rushingYards','touchdowns','firstDowns','thirdConversions','fourthConversions','sacks','interceptions','fieldGoals','returns','returnYards'].map(key=><tr key={key}><th>{STAT_LABELS[key]}</th>{['home','away'].map(teamSide=>{const t=box[teamSide].team;return <td key={teamSide}>{key==='thirdConversions'?rate(t.thirdConversions,t.thirdAttempts):key==='fourthConversions'?rate(t.fourthConversions,t.fourthAttempts):num(t[key])}</td>})}</tr>)}</tbody></table></div></>}</section>:<div className="empty"><h3>No completed games yet.</h3><p>Finish a game to save its box score here.</p></div>}</>:<section className="game-panel"><h3>{career.trackedGames} tracked games · {num(career.team.wins)} wins</h3><div className="career-summary">{['passingYards','rushingYards','touchdowns','thirdConversions','sacks','fieldGoals'].map(key=><div key={key}><strong>{num(career.team[key])}</strong><span>{STAT_LABELS[key]}</span></div>)}</div><p className="muted">Your franchise’s completed games. Released players retain their records. {career.partialGames?`${career.partialGames} games have partial tracking.`:''} {history.length>career.trackedGames?`${history.length-career.trackedGames} older games have scores only.`:''}</p></section>}
 {(page==='career'||box)&&<section className="game-panel"><div className="section-head"><h3>{page==='games'?'Game box score':'Player career leaders'}</h3>{page==='games'&&<select aria-label="Box score team" value={side} onChange={e=>{setSide(e.target.value);setPlayer(null)}}><option value="home">{game.name||'Your franchise'}</option><option value="away">{game.opponent}</option></select>}</div><div className="stats-filters"><select aria-label="Stat category" value={category} onChange={e=>{setCategory(e.target.value);setSort(groups[e.target.value][2]||groups[e.target.value][0])}}>{Object.keys(groups).map(name=><option key={name}>{name}</option>)}</select><input aria-label="Search player stats" placeholder="Search players" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="stats-scroll"><table className="box-table"><thead><tr><th>Player</th>{page==='career'&&<th>GP</th>}{keys.map(k=><th key={k}><button onClick={()=>setSort(k)}>{STAT_LABELS[k]}{sort===k?' ↓':''}</button></th>)}</tr></thead><tbody>{rows.map(p=><tr key={p.id}><th><button onClick={()=>setPlayer(p)}>{p.name}</button></th>{page==='career'&&<td>{p.stats.games}</td>}{keys.map(k=><td key={k}>{num(p.stats[k])}</td>)}</tr>)}</tbody></table></div>{!rows.length&&<p className="muted">No matching {category.toLowerCase()} stats yet.</p>}
 {player&&<section className="player-stat-detail"><div className="section-head"><h3>{player.name}</h3><button onClick={()=>setPlayer(null)}>Close player</button></div><dl className="stat-table">{Object.entries(player.stats).map(([key,n])=><div key={key}><dt>{STAT_LABELS[key]||key}</dt><dd>{num(n)}</dd></div>)}</dl>{page==='career'&&<><h4>Game-by-game record</h4>{history.filter(g=>g.boxScore?.home.players[player.id]).map(g=><button className="stats-game-link" key={g.id} onClick={()=>{setGameId(g.id);setSide('home');section('games')}}>vs {g.opponent} · {g.result} {g.score.home}–{g.score.away}<small>{keys.map(k=>`${STAT_LABELS[k]}: ${num(g.boxScore.home.players[player.id].stats[k])}`).join(' · ')}</small></button>)}</>}</section>}</section>}
 </>}
 </div>
}
